/* ATIVIDADE DE REVISÃO 

1 - TRAZER TODOS OS DADOS
2 - TRAZER O NOME DO LIVRO E O NOME DA EDITORA
3 - TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO
4 - TRAZER O NOME DO LIVRO E O NÚMERO DE PÁGINAS DOS LIVROS PÚBLICADOS POR AUTORES DO SEXO FEMININO
5 - TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO
6 - TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO (QUESTÃO DESAFIO)*/

/*LIVROS 

NOME DO LIVRO - CARACTER(30)
NOME DO AUTOR - CARACTER(30)
SEXO DO AUTOR - CARACTER (1)
NUMERO DE PAGINAS - NUMERICO(5)
NOME DA EDITORA - CARACTER(30)
VALOR DO LIVRO - NUMERICO(11)
ESTADO DA EDITORA - CARACTER (2)
ANO PUBLICA - NUMERICO (4)
*/
/* MODELAGEM FÍSICA */ 

/* CRIAR O BANCO DE DADOS */ 
CREATE DATABASE LIVRARIA; 

USE LIVRARIA; 
/* CRIANDO A TABELA */ 

CREATE TABLE TOPLIVROS( 
    LIVRO VARCHAR(30),
    AUTOR VARCHAR(30),
    SEXO  CHAR(1),
    PAGINAS INT(10),
    EDITORA VARCHAR(30),
    VALOR FLOAT(5),
    UF CHAR(2),
    ANO INT(4)
); 
/* VERIFICANDO A TABELA */ 
SHOW TABLES; 

INSERT INTO TOPLIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES ('CAVALEIRO REAL', 'ANA CLAUDIA', 'F', 465,'ATLAS', 49.9, 'RJ', 2009);
INSERT INTO TOPLIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES ('SQL PARA LEIGOS', 'JOÃO NUNES', 'M', 450,'ADDISON', 98, 'SP', 2018);
INSERT INTO TOPLIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES ('RECEITAS CASEIRAS', 'CELIA TAVARES', 'F', 210, 'ATLAS', 45, 'RJ', 2008);
INSERT INTO TOPLIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES ('PESSOAS EFETIVAS','EDUARDO SANTOS', 'M', 390, 'BETA', 78.99, 'RJ', 2018);
INSERT INTO TOPLIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES ('HABITOS SAÚDAVEIS', 'EDUARDO SANTOS', 'M', 630, 'BETA',150.98, 'RJ', 2019);
INSERT INTO TOPLIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES ('A CASA MARROM', 'HERMES MACEDO', 'M', 250, 'BUBBA', 60 , 'MG', 2016);
INSERT INTO TOPLIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES ('ESTACIO QUERIDO','GERALDO FRANCISCO','M',310,'INSGNIA',78.98,'ES',2011);
INSERT INTO TOPLIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES ('PRA SEMPRE AMIGAS','LEDA SILVA', 'F',510, 'INSGNIA', 78.98, 'ES', 2011);
INSERT INTO TOPLIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES ('COPAS INESQUECIVEIS','MARCOS ALCANTARA', 'M',200,'LARSON',130.98,'RS',2018);
INSERT INTO TOPLIVROS (LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) VALUES ('O PODER DA MENTE','CLARA MAFRA','F',120,'CONTINENTAL',56.58,'RS',2017);

/* 1 - TRAZER TODOS OS DADOS */ 
SELECT * FROM TOPLIVROS; 

/* 2 - TRAZER O NOME DO LIVRO E A EDITORA */ 

SELECT LIVRO, EDITORA FROM TOPLIVROS;

/* 3 - TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO */ 

SELECT LIVRO, UF FROM TOPLIVROS
WHERE SEXO = 'M'; 

/* 4 - TRAZER O NOME DO LIVRO E O NÚMERO DE PÁGINAS DOS LIVROS PÚBLICADOS POR AUTORES DO SEXO FEMININO */ 
 SELECT LIVRO, PAGINAS FROM TOPLIVROS
 WHERE SEXO = 'F';

/*5 - TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO*/
SELECT LIVRO, VALOR, EDITORA FROM TOPLIVROS
WHERE UF = 'SP';
/*6 - TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO (QUESTÃO DESAFIO)*/
/* AND E OR */ 
SELECT AUTOR, SEXO, UF FROM TOPLIVROS
WHERE SEXO = 'M'
AND UF ='SP'
OR UF ='RJ';