/*Filtrando valores nulos */ 

/* CRIANDO O BANCO DE DADOS, UTILIZAMOS O CREATE -- PARA CRIAR A BANCO DE DADOS */ 
create database modulo7;

/* UTILIZAMOS O USE PARA USAR O BANCO DE DADOS */ 
use modulo7;

/* CREATE TABLE -- PARA CRIAR UMA TABELA DENTRO DO BANCO DE DADOS */ 
create table funcionarios(
    idFuncionario integer,
    nome varchar(100),
    email varchar(100),
    sexo varchar(10),
    departamento varchar(100),
    admissao varchar(10),
    salario integer,
    cargo varchar(100),
    idRegiao int
);

/* QUANDO TRABALHAMOS COM UM BANCO DE DADOS PODE ACONTECER DE UM DADO ESTAR NULO OU VAZIO, NESTE MÓDULO APRENDEREMOS
COMO EXCLUIR ESSES DADOS NULOS. */ 

SELECT NOME, SEXO, DEPARTAMENTO
FROM FUNCIONARIOS
WHERE EMAIL IS NULL;

/* DESSA FORMA O BANCO IRÁ NOS RETORNAR TODOS OS DADOS QUE SÃO NULOS */ 

/* AGORA CASO, QUISERMOS OS DADOS QUE NÃO SÃO NULOS, OU SEJA TODOS QUE TEM AS INFORMAÇÕES
PODEMOS UTILIZAR O COMANDO */

SELECT NOME, SEXO, DEPARTAMENTO
FROM FUNCIONARIOS
WHERE EMAIL IS NOT NULL;

/* IS OU IS NOT NULL */ 

/* *****IMPORTANTE******** CLAUSULA UPDATE -- ATUALIZAR OS REGISTROS QUE JÁ ESTÃO NA TABELA! */
SELECT NOME, EMAIL
FROM CLIENTE; 

UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM'; /* IMPORTANTE - ESSES DADOS AQUI ATUALIZAM TODOS OS DADOS DE EMAIL */


/* ******** IMPORTANTE *********** O WHERE VAI SER SEU COMPANHEIRO PARA A VIDA INTEIRA */
/* AQUI NÓS SELECIONAMOS QUAL DADO NÓS QUEREMOS MUDAR */ 

 UPDATE FUNCIONARIOS
 SET EMAIL = 'TED@HOTMAIL.COM'
 WHERE NOME = 'TED';

 UPDATE FUNCIONARIOS
 SET EMAIL = 'JHONYMAXIMO@HOTMAIL.COM'
 WHERE NOME = 'JHONY';

 UPDATE FUNCIONARIOS
 SET EMAIL = 'GERALDBRUXO@HOTMAIL.COM'
 WHERE NOME = 'GERALD';

/* CLAUSULA DELETE */ 

/*PRIMEIRO VERIFICAMOS A QUANTIDADE DE DADOS QUE TEMOS */

SELECT COUNT(*) AS "QUANTIDADE DE FUNCIONARIOS"
FROM FUNCIONARIOS; 
/* TOTAL = 978 */

/* AGORA VEMOS OS DADOS QUE QUEREMOS EXCLUIR */

SELECT * FROM FUNCIONARIOS WHERE NOME = 'SPENCER';
/* CONTANDO QUANTOS DADOS TEM NO REGISTRO*/

SELECT COUNT(*) FROM FUNCIONARIOS
WHERE NOME='SPENCER';
/* TOTAL = 4 */

/* DELETANDO OS DADOS */ 

DELETE FROM FUNCIONARIOS
WHERE NOME = 'SPENCER';

/* VAMOS VERIFICAR NOVAMENTE OS DADOS DO REGISTRO */ 
SELECT COUNT(*) FROM FUNCIONARIOS
WHERE NOME='SPENCER';
/* TOTAL = 0 */ 

SELECT COUNT(*) AS "QUANTIDADE DE FUNCIONARIOS"
FROM FUNCIONARIOS; 
/* TOTAL = 974 */

/* AGORA VAMOS PEGAR CLIENTES COM O MESMO NOME COM DADOS DIFERENTES */ 
SELECT COUNT(*) FROM FUNCIONARIOS
WHERE NOME='ROSS';
/*TOTAL = 3 */ 

SELECT NOME, EMAIL, CARGO FROM FUNCIONARIOS
WHERE NOME ='ROSS';

/*- EXCLUIMOS DO BANCO APENAS O 'ROSS' COM O EMAIL RROSSNE@SALON.COM' */
DELETE FROM FUNCIONARIOS
WHERE NOME = 'ROSS' AND EMAIL = 'RROSSNE@SALON.COM';

SELECT COUNT(*) FROM FUNCIONARIOS
WHERE NOME='ROSS';
/* VALOR = 2 */ 


